version: '3'
services:
  mariadb:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=rdflib
  postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=rdflib
  rdflib:
    image: ropensci/rdflib:cli
    volumes: 
      - .:/data
    working_dir: /data
    links: 
      - postgres
      - mariadb
      



