version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose run rdflib R -e 'x <- devtools::check(); testthat::expect_length(x$errors,0); testthat::expect_length(x$warnings,0))'
